run tf-plan as a test

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -1,5 +1,10 @@
 version: 2.1
 
+parameters:
+  use-aws-orbs:
+    type: boolean
+    default: true
+
 orbs:
   aws-cli: circleci/aws-cli@4.1.3
   aws-ecs: circleci/aws-ecs@4.0.0
@@ -10,10 +15,39 @@ commands:
     steps:
        - aws-cli/setup:
             region: us-east-1
-            role_arn:  AWS_OIDC_ROLE
+            role_arn: AWS_OIDC_ROLE
             role_session_name: "CircleCI-${CIRCLE_WORKFLOW_ID}-${CIRCLE_JOB}"
   manual-push-to-ecr:
     steps:
+      - checkout
+      - run:
+          name: Build Docker image
+          command: |
+            docker build -t $ECS_DEMO_IMAGE .
+      - run:
+          name: Run Docker container on port 5000 in detached mode...
+          command: |
+            echo "Running container in detached mode..."
+            docker run -d -p $CONTAINER_PORT:$CONTAINER_PORT -e ENV_VAR1=$CIRCLE_USERNAME -e ENV_VAR2=$CIRCLE_BUILD_NUM $ECS_DEMO_IMAGE
+      - run: 
+          name: Perform Health Check
+          command: |
+             if curl http://localhost:$CONTAINER_PORT; then
+                     printf "\n\nHealth Check was successful.."
+             else
+                     echo "Request failed. Check if docker container is healthy..."
+                     exit 1
+             fi
+      - run: docker ps
+      - run: docker images
+      - run:
+          when: on_success
+          name: push to ECR if build is successful
+          command: |
+            aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $ECR_IMAGE_REPO
+            docker tag $ECS_DEMO_IMAGE:latest $ECR_IMAGE_REPO/$ECS_DEMO_IMAGE:latest
+            echo -e "\033[0;32mReady to push image to ECR....\033[0m"
+            docker push $ECR_IMAGE_REPO/$ECS_DEMO_IMAGE:latest
       - run:
           name: push to ECR if build is successful
           command: |
@@ -21,25 +55,7 @@ commands:
             docker tag $ECS_DEMO_IMAGE:latest $ECR_IMAGE_REPO/$ECS_DEMO_IMAGE:latest
             echo -e "\033[0;32mReady to push image to ECR....\033[0m"
             docker push $ECR_IMAGE_REPO/$ECS_DEMO_IMAGE:latest
-  
 
-parameters:
-  account-id:
-    type: string
-  ecs-image:
-    type: string
-    default: "ecs-demo-repo"
-  aws-default-region:
-    type: string
-    default: "us-east-1"
-  main-wf:
-    type: boolean
-    default: true
-  role-name:
-    type: string
-  workspace:
-    default: "terraform"
-    type: string
 
 executors:
   ubuntu-default:
@@ -51,56 +67,47 @@ executors:
       DOCKER_BULDKIT: "1"
       CONTAINER_PORT: 5000
 
-
-  terraform-docker:
+  tf-docker:
     docker:
       - image: hashicorp/terraform:1.8.3
-    resource_class: large
+    resource_class: small
 
 jobs: 
+  tf-plan:
+    executor: tf-docker
+    steps:
+      - checkout
+      - aws-cli/setup:
+          region: us-east-1
+          profile_name: circleci-ecs-deployments
+          role_arn: arn:aws:iam::992382483259:role/fieldeng_circleci_labs_oidc_oauth_role
+          role_session_name: "CircleCI-${CIRCLE_WORKFLOW_ID}-${CIRCLE_JOB}"
+      - run:
+          name: Run terraform plan
+          command: |
+               cd terraform
+               terraform init -input=false
+               terraform plan -out tfapply
+      - persist_to_workspace:
+          root: .
+          paths:
+            - .
+
   ecs-build:
     executor: ubuntu-default
     steps:
       - checkout
       - aws-ecr/build_and_push_image:
-          account_id: << pipeline.parameters.account-id >>
+          account_id: ACCOUNT_ID
           auth:
             - aws-cli/setup:
                 region: us-east-1
-                role_arn: << pipeline.parameters.role-name >>
+                role_arn: AWS_OIDC_ROLE
                 role_session_name: "CircleCI-${CIRCLE_WORKFLOW_ID}-${CIRCLE_JOB}"
                 profile_name: oidc
           no_output_timeout: 20m
           profile_name: oidc
           repo: ecs-demo-repo
-      #- run:
-      #    name: Build Docker image
-      #    command: |
-      #      docker build -t $ECS_DEMO_IMAGE .
-      #- run:
-      #    name: Run Docker container on port 5000 in detached mode...
-      #    command: |
-      #      echo "Running container in detached mode..."
-      #      docker run -d -p $CONTAINER_PORT:$CONTAINER_PORT -e ENV_VAR1=$CIRCLE_USERNAME -e ENV_VAR2=$CIRCLE_BUILD_NUM $ECS_DEMO_IMAGE
-      #- run: 
-      #    name: Perform Health Check
-      #    command: |
-      #       if curl http://localhost:$CONTAINER_PORT; then
-      #               printf "\n\nHealth Check was successful.."
-      #       else
-      #               echo "Request failed. Check if docker container is healthy..."
-      #               exit 1
-      #       fi
-      #- run: docker ps
-      #- run: docker images
-      #- run:
-      #    when: on_success
-      #    name: push to ECR if build is successful
-      #    command: |
-      #      aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $ECR_IMAGE_REPO
-      #      docker tag $ECS_DEMO_IMAGE:latest $ECR_IMAGE_REPO/$ECS_DEMO_IMAGE:latest
-      #      echo -e "\033[0;32mReady to push image to ECR....\033[0m"
-      #      docker push $ECR_IMAGE_REPO/$ECS_DEMO_IMAGE:latest
       - aws-ecs/update_task_definition_from_json:
           profile_name: oidc
           task_definition_json: my-task-definition.json
@@ -116,7 +123,6 @@ workflows:
   ecs:
     when: 
       and: 
-       - equal: [true, << pipeline.parameters.main-wf >>]
+       - equal: [true, << pipeline.parameters.use-aws-orbs >>]
     jobs:
-      - ecs-build:
-           context: fieldeng-aws-context
+      - tf-plan
